services:
  - type: web
    name: estimpro
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_PLACES_API_KEY
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD_HASH
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 10000